spring:
  profiles:
    include:
      - common
      - local
      - crypto
      - oauth2
      - secret

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: false
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    property-naming-strategy: SNAKE_CASE

custom:
  jwt:
    secret: ENC(JuKgHEVRxF4KNsrDCA5DPs99AsOaLbkLSmqVGbm1En8ahwd/S9QV8I+SrqeYwhMcH4dvFsOgfP5ug0MYuxpo5A==)
    access-expiration-time: 900000 # 15분 -> 15 * 60 * 1000
    refresh-expiration-time: 1296000000 # 15일 -> 15 * 24 * 60 * 60 * 1000

---

spring:
  config:
    activate:
      on-profile: oauth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(/NVz3t1aoMGO4L9F9MI017vxf8KcHfo3y/+xMWKfUAg1LcGiqMY6l0NvNXXPjKJC)
            client-secret: ENC(+c7I7VG9cIym6iwPEnZKIzpkTVmhDB/SbHBy5RO2fGSse9r7pauDqfzRrSrvnmv1)
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: kakao
            scope: account_email, profile_nickname
          google:
            client-id: ENC(ExgiUVdDUXj0bZHGzdwfzdo+FL+oltvojYYmQUoUE3Xy5aBfvrc4H6H5j3AkVOcqCS3uZlTFl+QMBVacaLXRQP0Orp/UvVnVf3GJLm0mYue3YZ0leancXPDw/w/6QwQw)
            client-secret: ENC(nOr263017o4m5RqiMKINIKOSUksOCtQ1rnVbaAuqUihdxV2x1lqUzUkMz2+aB5kP)
            scope: email, profile
          naver:
            client-id: ENC(lPu7dZZ8/5Nw+58vtKCPkVqWFFOavr41eEQ4iTZHeAM=)
            client-secret: ENC(C3vESb/5wp0oAS5Xv0+31pE002otp/aN)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            clientAuthenticationMethod: client_secret_post
            authorization-grant-type: authorization_code
            client-name: naver
            scope: email, nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response