spring:
  profiles:
    include:
        - crypto
        - oauth2
        - secret
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: false
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    property-naming-strategy: SNAKE_CASE

custom:
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: ENC(mpeeRapq7w6gKKs4vxfw7GqJiqDz+/7x81U0yECpUinUZclGaYZ6WRJ+ZgXuMTb9ZIjZBtFnAnRJdhVEuH1lJA==)
    token:
      access-expiration-time: 300000 # 3분 ->  5 * 60 * 1000
      refresh-expiration-time: 604800000 # 7일 -> 7 * 24 * 60 * 60 * 1000

---

spring:
  config:
    activate:
      on-profile: oauth2
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(HX5zlr1ZxSaw/uq99/UH08i8gRfXzqHT+E+n80V39hztnsXmA5Ulc2mmyk0mXUmK)
            client-secret: ENC(Cu3l+7WzuPd8PReb6pcObPFKw9BakzEJvmDO3bwqe9pdMpuPpYSUsl/2yqfTnSOV)
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: kakao
            scope: account_email, profile_nickname, profile_image
          google:
            client-id: ENC(7vERj35mMHmIKeEsaIsy3u0NZH4LmUdTKSgakSRlZObdo4TPafSxTV/8Ef+yXRUW/4RTpaK6pvDggnJkzIaM28913xaYwBt6FMdlKKenZsuEEehazNSN6w==)
            client-secret: ENC(UgyFPoakfMpsJ2r92AUD/3ZNP4rIMUIL+i5/yeFKpRH2DbRQx4RgEgT3ny8JFmM/)
            scope: email, profile
          naver:
            client-id: ENC(03hDNDCgRZOrvQh9Mm2ETL+hYUKXnBjGIJId8oz9ymA=)
            client-secret: ENC(2w7/3KWbzbqwBKZLAyQfKMITJUdmI55j)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            clientAuthenticationMethod: client_secret_post
            authorization-grant-type: authorization_code
            client-name: naver
            scope: email, nickname, profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response