spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    group:
      local:
        - common
        - account
        - crypto
        - oauth2
        - secret
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/speech
    username: speech.application
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      show_sql: true
      hibernate:
        format_sql: true
        use_sql_comments: true
file:
  base-path: ./data
  thumbnail-path: /thumbnails
  audio-path: /audios
