custom:
  base-url: http://localhost:8080
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    password: 1234


---

spring:
  config:
    activate:
      on-profile: prod
custom:
  base-url: http://localhost:8080
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
    password: 1234
